#!/usr/bin/python3
import sys
from math import *

def do_all():
    nb1 = float(sys.argv[1])
    nb2 = float(sys.argv[2])
    nb3 = float(sys.argv[3])
    nb4 = float(sys.argv[4])
    tmp = 0.0
    while(1):
        print("Enter next value: ")
        user = input()
        if (user == "END"):
            exit(0)
        try:
            tmp = float(user)
        except:
            print("only number")
            exit(84)
        

def help():
    print("USAGE\n\t./206neutrinos n a h sd\n")
    print("DESCRIPTION\n\tn\tnumber of values")
    print("\ta\tarithmetic mean")
    print("\th\tharmonic mean")
    print("\tsd\tstandard deviation")
    exit(0)

def check_error():
    if (sys.argv[1] == "-h"):
        help()
    if (len(sys.argv) < 5):
        exit(84)
    try:
        nb1 = float(sys.argv[1])
        nb2 = float(sys.argv[2])
        nb3 = float(sys.argv[3])
        nb4 = float(sys.argv[4])
    except:
        exit(84)
    if (nb1 < 0 or nb2 < 0 or nb3 < 0 or nb4 < 0):
        exit(84)

def main():
    if (len(sys.argv) < 2):
        exit(84)
    check_error()
    do_all()

if __name__ == '__main__':
    main()